// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jp.tamagotchi.proto.business/service/petOwnership/petOwnershipService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Jp.Tamagotchi.Business.Shared.Services.PetOwnership {

  /// <summary>Holder for reflection information generated from jp.tamagotchi.proto.business/service/petOwnership/petOwnershipService.proto</summary>
  public static partial class PetOwnershipServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for jp.tamagotchi.proto.business/service/petOwnership/petOwnershipService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PetOwnershipServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CktqcC50YW1hZ290Y2hpLnByb3RvLmJ1c2luZXNzL3NlcnZpY2UvcGV0T3du",
            "ZXJzaGlwL3BldE93bmVyc2hpcFNlcnZpY2UucHJvdG8SM2pwLnRhbWFnb3Rj",
            "aGkuYnVzaW5lc3Muc2hhcmVkLnNlcnZpY2VzLnBldE93bmVyc2hpcBpJanAu",
            "dGFtYWdvdGNoaS5wcm90by5idXNpbmVzcy9zZXJ2aWNlL3BldE93bmVyc2hp",
            "cC9wZXRPd25lcnNoaXBNb2RlbC5wcm90byJyChdTYXZlUGV0T3duZXJzaGlw",
            "UmVxdWVzdBJXCgxwZXRPd25lcnNoaXAYASABKAsyQS5qcC50YW1hZ290Y2hp",
            "LmJ1c2luZXNzLnNoYXJlZC5zZXJ2aWNlcy5wZXRPd25lcnNoaXAuUGV0T3du",
            "ZXJzaGlwIpcBChhTYXZlUGV0T3duZXJzaGlwUmVzcG9uc2USEQoJc3VjZXNz",
            "ZnVsGAEgASgIEg8KB21lc3NhZ2UYAiABKAkSVwoMcGV0T3duZXJzaGlwGAMg",
            "ASgLMkEuanAudGFtYWdvdGNoaS5idXNpbmVzcy5zaGFyZWQuc2VydmljZXMu",
            "cGV0T3duZXJzaGlwLlBldE93bmVyc2hpcCJ7ChdHZXRQZXRPd25lcnNoaXBz",
            "UmVxdWVzdBIMCgRzaXplGAEgASgFElIKB2V4YW1wbGUYAiABKAsyQS5qcC50",
            "YW1hZ290Y2hpLmJ1c2luZXNzLnNoYXJlZC5zZXJ2aWNlcy5wZXRPd25lcnNo",
            "aXAuUGV0T3duZXJzaGlwIoYBChhHZXRQZXRPd25lcnNoaXBzUmVzcG9uc2US",
            "EQoJc3VjZXNzZnVsGAEgASgIElcKDHBldE93bmVyc2hpcBgCIAMoCzJBLmpw",
            "LnRhbWFnb3RjaGkuYnVzaW5lc3Muc2hhcmVkLnNlcnZpY2VzLnBldE93bmVy",
            "c2hpcC5QZXRPd25lcnNoaXAy+QIKE1BldE93bmVyc2hpcFNlcnZpY2USrwEK",
            "EFNhdmVQZXRPd25lcnNoaXASTC5qcC50YW1hZ290Y2hpLmJ1c2luZXNzLnNo",
            "YXJlZC5zZXJ2aWNlcy5wZXRPd25lcnNoaXAuU2F2ZVBldE93bmVyc2hpcFJl",
            "cXVlc3QaTS5qcC50YW1hZ290Y2hpLmJ1c2luZXNzLnNoYXJlZC5zZXJ2aWNl",
            "cy5wZXRPd25lcnNoaXAuU2F2ZVBldE93bmVyc2hpcFJlc3BvbnNlEq8BChBH",
            "ZXRQZXRPd25lcnNoaXBzEkwuanAudGFtYWdvdGNoaS5idXNpbmVzcy5zaGFy",
            "ZWQuc2VydmljZXMucGV0T3duZXJzaGlwLkdldFBldE93bmVyc2hpcHNSZXF1",
            "ZXN0Gk0uanAudGFtYWdvdGNoaS5idXNpbmVzcy5zaGFyZWQuc2VydmljZXMu",
            "cGV0T3duZXJzaGlwLkdldFBldE93bmVyc2hpcHNSZXNwb25zZUI1CjNqcC50",
            "YW1hZ290Y2hpLmJ1c2luZXNzLnNoYXJlZC5zZXJ2aWNlcy5wZXRPd25lcnNo",
            "aXBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnershipModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest), global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest.Parser, new[]{ "PetOwnership" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse), global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse.Parser, new[]{ "Sucessful", "Message", "PetOwnership" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest), global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest.Parser, new[]{ "Size", "Example" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse), global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse.Parser, new[]{ "Sucessful", "PetOwnership" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SavePetOwnershipRequest : pb::IMessage<SavePetOwnershipRequest> {
    private static readonly pb::MessageParser<SavePetOwnershipRequest> _parser = new pb::MessageParser<SavePetOwnershipRequest>(() => new SavePetOwnershipRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SavePetOwnershipRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnershipServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SavePetOwnershipRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SavePetOwnershipRequest(SavePetOwnershipRequest other) : this() {
      PetOwnership = other.petOwnership_ != null ? other.PetOwnership.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SavePetOwnershipRequest Clone() {
      return new SavePetOwnershipRequest(this);
    }

    /// <summary>Field number for the "petOwnership" field.</summary>
    public const int PetOwnershipFieldNumber = 1;
    private global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership petOwnership_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership PetOwnership {
      get { return petOwnership_; }
      set {
        petOwnership_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SavePetOwnershipRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SavePetOwnershipRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(PetOwnership, other.PetOwnership)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (petOwnership_ != null) hash ^= PetOwnership.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (petOwnership_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(PetOwnership);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (petOwnership_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PetOwnership);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SavePetOwnershipRequest other) {
      if (other == null) {
        return;
      }
      if (other.petOwnership_ != null) {
        if (petOwnership_ == null) {
          petOwnership_ = new global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership();
        }
        PetOwnership.MergeFrom(other.PetOwnership);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (petOwnership_ == null) {
              petOwnership_ = new global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership();
            }
            input.ReadMessage(petOwnership_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SavePetOwnershipResponse : pb::IMessage<SavePetOwnershipResponse> {
    private static readonly pb::MessageParser<SavePetOwnershipResponse> _parser = new pb::MessageParser<SavePetOwnershipResponse>(() => new SavePetOwnershipResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SavePetOwnershipResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnershipServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SavePetOwnershipResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SavePetOwnershipResponse(SavePetOwnershipResponse other) : this() {
      sucessful_ = other.sucessful_;
      message_ = other.message_;
      PetOwnership = other.petOwnership_ != null ? other.PetOwnership.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SavePetOwnershipResponse Clone() {
      return new SavePetOwnershipResponse(this);
    }

    /// <summary>Field number for the "sucessful" field.</summary>
    public const int SucessfulFieldNumber = 1;
    private bool sucessful_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Sucessful {
      get { return sucessful_; }
      set {
        sucessful_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "petOwnership" field.</summary>
    public const int PetOwnershipFieldNumber = 3;
    private global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership petOwnership_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership PetOwnership {
      get { return petOwnership_; }
      set {
        petOwnership_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SavePetOwnershipResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SavePetOwnershipResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sucessful != other.Sucessful) return false;
      if (Message != other.Message) return false;
      if (!object.Equals(PetOwnership, other.PetOwnership)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Sucessful != false) hash ^= Sucessful.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (petOwnership_ != null) hash ^= PetOwnership.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Sucessful != false) {
        output.WriteRawTag(8);
        output.WriteBool(Sucessful);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (petOwnership_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PetOwnership);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Sucessful != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (petOwnership_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PetOwnership);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SavePetOwnershipResponse other) {
      if (other == null) {
        return;
      }
      if (other.Sucessful != false) {
        Sucessful = other.Sucessful;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.petOwnership_ != null) {
        if (petOwnership_ == null) {
          petOwnership_ = new global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership();
        }
        PetOwnership.MergeFrom(other.PetOwnership);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Sucessful = input.ReadBool();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            if (petOwnership_ == null) {
              petOwnership_ = new global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership();
            }
            input.ReadMessage(petOwnership_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetPetOwnershipsRequest : pb::IMessage<GetPetOwnershipsRequest> {
    private static readonly pb::MessageParser<GetPetOwnershipsRequest> _parser = new pb::MessageParser<GetPetOwnershipsRequest>(() => new GetPetOwnershipsRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetPetOwnershipsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnershipServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPetOwnershipsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPetOwnershipsRequest(GetPetOwnershipsRequest other) : this() {
      size_ = other.size_;
      Example = other.example_ != null ? other.Example.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPetOwnershipsRequest Clone() {
      return new GetPetOwnershipsRequest(this);
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 1;
    private int size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "example" field.</summary>
    public const int ExampleFieldNumber = 2;
    private global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership example_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership Example {
      get { return example_; }
      set {
        example_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetPetOwnershipsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetPetOwnershipsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Size != other.Size) return false;
      if (!object.Equals(Example, other.Example)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Size != 0) hash ^= Size.GetHashCode();
      if (example_ != null) hash ^= Example.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Size != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Size);
      }
      if (example_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Example);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Size != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Size);
      }
      if (example_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Example);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetPetOwnershipsRequest other) {
      if (other == null) {
        return;
      }
      if (other.Size != 0) {
        Size = other.Size;
      }
      if (other.example_ != null) {
        if (example_ == null) {
          example_ = new global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership();
        }
        Example.MergeFrom(other.Example);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Size = input.ReadInt32();
            break;
          }
          case 18: {
            if (example_ == null) {
              example_ = new global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership();
            }
            input.ReadMessage(example_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetPetOwnershipsResponse : pb::IMessage<GetPetOwnershipsResponse> {
    private static readonly pb::MessageParser<GetPetOwnershipsResponse> _parser = new pb::MessageParser<GetPetOwnershipsResponse>(() => new GetPetOwnershipsResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetPetOwnershipsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnershipServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPetOwnershipsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPetOwnershipsResponse(GetPetOwnershipsResponse other) : this() {
      sucessful_ = other.sucessful_;
      petOwnership_ = other.petOwnership_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPetOwnershipsResponse Clone() {
      return new GetPetOwnershipsResponse(this);
    }

    /// <summary>Field number for the "sucessful" field.</summary>
    public const int SucessfulFieldNumber = 1;
    private bool sucessful_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Sucessful {
      get { return sucessful_; }
      set {
        sucessful_ = value;
      }
    }

    /// <summary>Field number for the "petOwnership" field.</summary>
    public const int PetOwnershipFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership> _repeated_petOwnership_codec
        = pb::FieldCodec.ForMessage(18, global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership.Parser);
    private readonly pbc::RepeatedField<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership> petOwnership_ = new pbc::RepeatedField<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnership> PetOwnership {
      get { return petOwnership_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetPetOwnershipsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetPetOwnershipsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sucessful != other.Sucessful) return false;
      if(!petOwnership_.Equals(other.petOwnership_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Sucessful != false) hash ^= Sucessful.GetHashCode();
      hash ^= petOwnership_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Sucessful != false) {
        output.WriteRawTag(8);
        output.WriteBool(Sucessful);
      }
      petOwnership_.WriteTo(output, _repeated_petOwnership_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Sucessful != false) {
        size += 1 + 1;
      }
      size += petOwnership_.CalculateSize(_repeated_petOwnership_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetPetOwnershipsResponse other) {
      if (other == null) {
        return;
      }
      if (other.Sucessful != false) {
        Sucessful = other.Sucessful;
      }
      petOwnership_.Add(other.petOwnership_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Sucessful = input.ReadBool();
            break;
          }
          case 18: {
            petOwnership_.AddEntriesFrom(input, _repeated_petOwnership_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
