// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: jp.tamagotchi.proto.business/service/petOwnership/petOwnershipService.proto
// </auto-generated>
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Jp.Tamagotchi.Business.Shared.Services.PetOwnership {
  public static partial class PetOwnershipService
  {
    static readonly string __ServiceName = "jp.tamagotchi.business.shared.services.petOwnership.PetOwnershipService";

    static readonly grpc::Marshaller<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest> __Marshaller_SavePetOwnershipRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse> __Marshaller_SavePetOwnershipResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest> __Marshaller_GetPetOwnershipsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse> __Marshaller_GetPetOwnershipsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest, global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse> __Method_SavePetOwnership = new grpc::Method<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest, global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SavePetOwnership",
        __Marshaller_SavePetOwnershipRequest,
        __Marshaller_SavePetOwnershipResponse);

    static readonly grpc::Method<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest, global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse> __Method_GetPetOwnerships = new grpc::Method<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest, global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetPetOwnerships",
        __Marshaller_GetPetOwnershipsRequest,
        __Marshaller_GetPetOwnershipsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.PetOwnershipServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PetOwnershipService</summary>
    public abstract partial class PetOwnershipServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse> SavePetOwnership(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse> GetPetOwnerships(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PetOwnershipService</summary>
    public partial class PetOwnershipServiceClient : grpc::ClientBase<PetOwnershipServiceClient>
    {
      /// <summary>Creates a new client for PetOwnershipService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PetOwnershipServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PetOwnershipService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PetOwnershipServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PetOwnershipServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PetOwnershipServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse SavePetOwnership(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SavePetOwnership(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse SavePetOwnership(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SavePetOwnership, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse> SavePetOwnershipAsync(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SavePetOwnershipAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipResponse> SavePetOwnershipAsync(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.SavePetOwnershipRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SavePetOwnership, null, options, request);
      }
      public virtual global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse GetPetOwnerships(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetPetOwnerships(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse GetPetOwnerships(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetPetOwnerships, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse> GetPetOwnershipsAsync(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetPetOwnershipsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsResponse> GetPetOwnershipsAsync(global::Jp.Tamagotchi.Business.Shared.Services.PetOwnership.GetPetOwnershipsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetPetOwnerships, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PetOwnershipServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PetOwnershipServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PetOwnershipServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SavePetOwnership, serviceImpl.SavePetOwnership)
          .AddMethod(__Method_GetPetOwnerships, serviceImpl.GetPetOwnerships).Build();
    }

  }
}
#endregion
