// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: jp.tamagotchi.proto.business/service/user/userService.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Jp.Tamagotchi.Business.Shared.Services.User {

  /// <summary>Holder for reflection information generated from jp.tamagotchi.proto.business/service/user/userService.proto</summary>
  public static partial class UserServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for jp.tamagotchi.proto.business/service/user/userService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjtqcC50YW1hZ290Y2hpLnByb3RvLmJ1c2luZXNzL3NlcnZpY2UvdXNlci91",
            "c2VyU2VydmljZS5wcm90bxIranAudGFtYWdvdGNoaS5idXNpbmVzcy5zaGFy",
            "ZWQuc2VydmljZXMudXNlcho5anAudGFtYWdvdGNoaS5wcm90by5idXNpbmVz",
            "cy9zZXJ2aWNlL3VzZXIvdXNlck1vZGVsLnByb3RvIlIKD1NhdmVVc2VyUmVx",
            "dWVzdBI/CgR1c2VyGAEgASgLMjEuanAudGFtYWdvdGNoaS5idXNpbmVzcy5z",
            "aGFyZWQuc2VydmljZXMudXNlci5Vc2VyIncKEFNhdmVVc2VyUmVzcG9uc2US",
            "EQoJc3VjZXNzZnVsGAEgASgIEg8KB21lc3NhZ2UYAiABKAkSPwoEdXNlchgD",
            "IAEoCzIxLmpwLnRhbWFnb3RjaGkuYnVzaW5lc3Muc2hhcmVkLnNlcnZpY2Vz",
            "LnVzZXIuVXNlciJjCg9HZXRVc2Vyc1JlcXVlc3QSDAoEc2l6ZRgBIAEoBRJC",
            "CgdleGFtcGxlGAIgASgLMjEuanAudGFtYWdvdGNoaS5idXNpbmVzcy5zaGFy",
            "ZWQuc2VydmljZXMudXNlci5Vc2VyImYKEEdldFVzZXJzUmVzcG9uc2USEQoJ",
            "c3VjZXNzZnVsGAEgASgIEj8KBHVzZXIYAiADKAsyMS5qcC50YW1hZ290Y2hp",
            "LmJ1c2luZXNzLnNoYXJlZC5zZXJ2aWNlcy51c2VyLlVzZXIyoQIKC1VzZXJT",
            "ZXJ2aWNlEocBCghTYXZlVXNlchI8LmpwLnRhbWFnb3RjaGkuYnVzaW5lc3Mu",
            "c2hhcmVkLnNlcnZpY2VzLnVzZXIuU2F2ZVVzZXJSZXF1ZXN0Gj0uanAudGFt",
            "YWdvdGNoaS5idXNpbmVzcy5zaGFyZWQuc2VydmljZXMudXNlci5TYXZlVXNl",
            "clJlc3BvbnNlEocBCghHZXRVc2VycxI8LmpwLnRhbWFnb3RjaGkuYnVzaW5l",
            "c3Muc2hhcmVkLnNlcnZpY2VzLnVzZXIuR2V0VXNlcnNSZXF1ZXN0Gj0uanAu",
            "dGFtYWdvdGNoaS5idXNpbmVzcy5zaGFyZWQuc2VydmljZXMudXNlci5HZXRV",
            "c2Vyc1Jlc3BvbnNlQi0KK2pwLnRhbWFnb3RjaGkuYnVzaW5lc3Muc2hhcmVk",
            "LnNlcnZpY2VzLnVzZXJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Jp.Tamagotchi.Business.Shared.Services.User.UserModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Jp.Tamagotchi.Business.Shared.Services.User.SaveUserRequest), global::Jp.Tamagotchi.Business.Shared.Services.User.SaveUserRequest.Parser, new[]{ "User" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jp.Tamagotchi.Business.Shared.Services.User.SaveUserResponse), global::Jp.Tamagotchi.Business.Shared.Services.User.SaveUserResponse.Parser, new[]{ "Sucessful", "Message", "User" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jp.Tamagotchi.Business.Shared.Services.User.GetUsersRequest), global::Jp.Tamagotchi.Business.Shared.Services.User.GetUsersRequest.Parser, new[]{ "Size", "Example" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Jp.Tamagotchi.Business.Shared.Services.User.GetUsersResponse), global::Jp.Tamagotchi.Business.Shared.Services.User.GetUsersResponse.Parser, new[]{ "Sucessful", "User" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SaveUserRequest : pb::IMessage<SaveUserRequest> {
    private static readonly pb::MessageParser<SaveUserRequest> _parser = new pb::MessageParser<SaveUserRequest>(() => new SaveUserRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SaveUserRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jp.Tamagotchi.Business.Shared.Services.User.UserServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveUserRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveUserRequest(SaveUserRequest other) : this() {
      User = other.user_ != null ? other.User.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveUserRequest Clone() {
      return new SaveUserRequest(this);
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 1;
    private global::Jp.Tamagotchi.Business.Shared.Services.User.User user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Jp.Tamagotchi.Business.Shared.Services.User.User User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SaveUserRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SaveUserRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(User, other.User)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (user_ != null) hash ^= User.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (user_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(User);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SaveUserRequest other) {
      if (other == null) {
        return;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          user_ = new global::Jp.Tamagotchi.Business.Shared.Services.User.User();
        }
        User.MergeFrom(other.User);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (user_ == null) {
              user_ = new global::Jp.Tamagotchi.Business.Shared.Services.User.User();
            }
            input.ReadMessage(user_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SaveUserResponse : pb::IMessage<SaveUserResponse> {
    private static readonly pb::MessageParser<SaveUserResponse> _parser = new pb::MessageParser<SaveUserResponse>(() => new SaveUserResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SaveUserResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jp.Tamagotchi.Business.Shared.Services.User.UserServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveUserResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveUserResponse(SaveUserResponse other) : this() {
      sucessful_ = other.sucessful_;
      message_ = other.message_;
      User = other.user_ != null ? other.User.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SaveUserResponse Clone() {
      return new SaveUserResponse(this);
    }

    /// <summary>Field number for the "sucessful" field.</summary>
    public const int SucessfulFieldNumber = 1;
    private bool sucessful_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Sucessful {
      get { return sucessful_; }
      set {
        sucessful_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 3;
    private global::Jp.Tamagotchi.Business.Shared.Services.User.User user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Jp.Tamagotchi.Business.Shared.Services.User.User User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SaveUserResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SaveUserResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sucessful != other.Sucessful) return false;
      if (Message != other.Message) return false;
      if (!object.Equals(User, other.User)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Sucessful != false) hash ^= Sucessful.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Sucessful != false) {
        output.WriteRawTag(8);
        output.WriteBool(Sucessful);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (user_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(User);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Sucessful != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SaveUserResponse other) {
      if (other == null) {
        return;
      }
      if (other.Sucessful != false) {
        Sucessful = other.Sucessful;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          user_ = new global::Jp.Tamagotchi.Business.Shared.Services.User.User();
        }
        User.MergeFrom(other.User);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Sucessful = input.ReadBool();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            if (user_ == null) {
              user_ = new global::Jp.Tamagotchi.Business.Shared.Services.User.User();
            }
            input.ReadMessage(user_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetUsersRequest : pb::IMessage<GetUsersRequest> {
    private static readonly pb::MessageParser<GetUsersRequest> _parser = new pb::MessageParser<GetUsersRequest>(() => new GetUsersRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetUsersRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jp.Tamagotchi.Business.Shared.Services.User.UserServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUsersRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUsersRequest(GetUsersRequest other) : this() {
      size_ = other.size_;
      Example = other.example_ != null ? other.Example.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUsersRequest Clone() {
      return new GetUsersRequest(this);
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 1;
    private int size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "example" field.</summary>
    public const int ExampleFieldNumber = 2;
    private global::Jp.Tamagotchi.Business.Shared.Services.User.User example_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Jp.Tamagotchi.Business.Shared.Services.User.User Example {
      get { return example_; }
      set {
        example_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetUsersRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetUsersRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Size != other.Size) return false;
      if (!object.Equals(Example, other.Example)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Size != 0) hash ^= Size.GetHashCode();
      if (example_ != null) hash ^= Example.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Size != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Size);
      }
      if (example_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Example);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Size != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Size);
      }
      if (example_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Example);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetUsersRequest other) {
      if (other == null) {
        return;
      }
      if (other.Size != 0) {
        Size = other.Size;
      }
      if (other.example_ != null) {
        if (example_ == null) {
          example_ = new global::Jp.Tamagotchi.Business.Shared.Services.User.User();
        }
        Example.MergeFrom(other.Example);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Size = input.ReadInt32();
            break;
          }
          case 18: {
            if (example_ == null) {
              example_ = new global::Jp.Tamagotchi.Business.Shared.Services.User.User();
            }
            input.ReadMessage(example_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetUsersResponse : pb::IMessage<GetUsersResponse> {
    private static readonly pb::MessageParser<GetUsersResponse> _parser = new pb::MessageParser<GetUsersResponse>(() => new GetUsersResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetUsersResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Jp.Tamagotchi.Business.Shared.Services.User.UserServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUsersResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUsersResponse(GetUsersResponse other) : this() {
      sucessful_ = other.sucessful_;
      user_ = other.user_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetUsersResponse Clone() {
      return new GetUsersResponse(this);
    }

    /// <summary>Field number for the "sucessful" field.</summary>
    public const int SucessfulFieldNumber = 1;
    private bool sucessful_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Sucessful {
      get { return sucessful_; }
      set {
        sucessful_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Jp.Tamagotchi.Business.Shared.Services.User.User> _repeated_user_codec
        = pb::FieldCodec.ForMessage(18, global::Jp.Tamagotchi.Business.Shared.Services.User.User.Parser);
    private readonly pbc::RepeatedField<global::Jp.Tamagotchi.Business.Shared.Services.User.User> user_ = new pbc::RepeatedField<global::Jp.Tamagotchi.Business.Shared.Services.User.User>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Jp.Tamagotchi.Business.Shared.Services.User.User> User {
      get { return user_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetUsersResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetUsersResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sucessful != other.Sucessful) return false;
      if(!user_.Equals(other.user_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Sucessful != false) hash ^= Sucessful.GetHashCode();
      hash ^= user_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Sucessful != false) {
        output.WriteRawTag(8);
        output.WriteBool(Sucessful);
      }
      user_.WriteTo(output, _repeated_user_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Sucessful != false) {
        size += 1 + 1;
      }
      size += user_.CalculateSize(_repeated_user_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetUsersResponse other) {
      if (other == null) {
        return;
      }
      if (other.Sucessful != false) {
        Sucessful = other.Sucessful;
      }
      user_.Add(other.user_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Sucessful = input.ReadBool();
            break;
          }
          case 18: {
            user_.AddEntriesFrom(input, _repeated_user_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
